package com.sahay.ai.ui

object Localization {
    private val dict = mapOf(
        "English" to mapOf(),
        "हिन्दी" to mapOf(
            "SAHAY-AI" to "सहाय-एआई",
            "Public Trust Infrastructure" to "सार्वजनिक विश्वास अवसंरचना",
            "Select Portal Access" to "पोर्टल एक्सेस चुनें",
            "Victim/Citizen" to "पीड़ित/नागरिक",
            "Access your journey & support" to "अपनी यात्रा और समर्थन तक पहुंचें",
            "Official Portal" to "आधिकारिक पोर्टल",
            "Manage active case queues" to "सक्रिय केस कतार प्रबंधित करें",
            "Preferred Language" to "पसंदीदा भाषा",
            "Select your communication language" to "अपनी संचार भाषा चुनें",
            "Continue" to "जारी रखें",
            "Your choice. Your control." to "आपकी पसंद। आपका नियंत्रण।",
            "SAHAY-AI uses your check-ins to understand changes in your wellbeing. Your information is protected and accessed only by authorized personnel." to "सहाय-एआई आपके कल्याण को समझने के लिए चेक-इन का उपयोग करता है। आपकी जानकारी सुरक्षित है।",
            "CONSENT-BASED — You choose whether to participate." to "सहमति आधारित — आप चुनते हैं कि भाग लेना है या नहीं।",
            "PRIVATE — Your information is protected." to "निजी — आपकी जानकारी सुरक्षित है।",
            "HUMAN SUPPORT — AI signals are reviewed by authorized people." to "मानवीय सहायता — एआई संकेतों की समीक्षा प्राधिकृत लोगों द्वारा की जाती है।",
            "I understand and consent to wellbeing monitoring." to "मैं समझता/समझती हूँ और कल्याण निगरानी के लिए सहमति देता/देती हूँ।",
            "Wellbeing monitoring requires your consent to continue." to "कल्याण निगरानी जारी रखने के लिए आपकी सहमति आवश्यक है।",
            "Give Consent" to "सहमति दें",
            "Not Now" to "अभी नहीं",
            "Registration & Linkage" to "पंजीकरण और जुड़ाव",
            "Link your secure case record" to "अपना सुरक्षित केस रिकॉर्ड लिंक करें",
            "Full Name" to "पूरा नाम",
            "Enter your full name" to "अपना पूरा नाम दर्ज करें",
            "Mobile Number" to "मोबाइल नंबर",
            "Enter your mobile number" to "अपना मोबाइल नंबर दर्ज करें",
            "Case ID" to "केस आईडी",
            "Enter your case ID" to "अपना केस आईडी दर्ज करें",
            "Trusted Person’s Mobile Number" to "विश्वसनीय व्यक्ति का मोबाइल नंबर",
            "Enter trusted person’s number" to "विश्वसनीय व्यक्ति का नंबर दर्ज करें",
            "You may provide a trusted person’s number for urgent support. This is optional." to "आप तत्काल सहायता के लिए एक विश्वसनीय व्यक्ति का नंबर प्रदान कर सकते हैं। यह वैकल्पिक है।",
            "Is this you? Log in securely" to "क्या यह आप हैं? सुरक्षित रूप से लॉग इन करें",
            "Link Profile" to "प्रोफ़ाइल लिंक करें",
            "You’re all set" to "आपका काम हो गया",
            "Your details have been securely saved. You can now begin your wellbeing check-ins and access support." to "आपका विवरण सुरक्षित रूप से सहेजा गया है। अब आप शुरू कर सकते हैं।",
            "Go to My Dashboard" to "मेरे डैशबोर्ड पर जाएं",
            "HOME" to "होम",
            "CHAT" to "चैट",
            "JOURNEY" to "यात्रा",
            "SUPPORT" to "सहायता",
            "PROFILE" to "प्रोफ़ाइल",
            "Good evening." to "शुभ संध्या।",
            "How are you doing today?" to "आज आप कैसे हैं?",
            "TODAY'S CHECK-IN" to "आज का चेक-इन",
            "Take a moment to tell us how you are feeling." to "हमें बताएं कि आप कैसा महसूस कर रहे हैं।",
            "Start Check-in" to "चेक-इन शुरू करें",
            "OTHER WAYS TO CONNECT" to "जुड़ने के अन्य तरीके",
            "Talk to SAHAY" to "सहाय से बात करें",
            "VOICE" to "आवाज़",
            "Speak instead" to "इसके बजाय बोलें",
            "CALL" to "कॉल करें",
            "Scheduled Call" to "निर्धारित कॉल",
            "Last Check-in" to "अंतिम चेक-इन",
            "Distress Score" to "संकट स्कोर",
            "Message SAHAY-AI..." to "सहाय-एआई को संदेश भेजें...",
            "Your Legal Journey" to "आपकी कानूनी यात्रा",
            "Case Status" to "केस की स्थिति",
            "Timeline" to "समयरेखा",
            "Support Services" to "सहायता सेवाएँ",
            "Emergency SOS" to "आपातकालीन SOS",
            "Trigger immediate official response" to "तत्काल आधिकारिक प्रतिक्रिया ट्रिगर करें",
            "Trusted Contacts" to "विश्वसनीय संपर्क",
            "Profile & Settings" to "प्रोफ़ाइल और सेटिंग्स",
            "Secure Sign Out" to "सुरक्षित साइन आउट",
            "Wellbeing Check-in" to "कल्याण चेक-इन",
            "On a scale from 0 to 100, where 100 corresponds to extreme distress, how do you feel today?" to "0 से 100 के पैमाने पर, जहां 100 का मतलब अत्यधिक संकट है, आज आप कैसा महसूस करते हैं?",
            "Score (0-100)" to "स्कोर (0-100)",
            "Submit Securely" to "सुरक्षित रूप से सबमिट करें",
            "Cancel" to "रद्द करें",
            "Stable" to "स्थिर",
            "Supported" to "समर्थित"
        ),
        "தமிழ்" to mapOf(
            "SAHAY-AI" to "சஹாய்-AI",
            "Public Trust Infrastructure" to "பொது நம்பிக்கைக் கட்டமைப்பு",
            "Select Portal Access" to "போர்டல் அணுகலைத் தேர்ந்தெடுக்கவும்",
            "Victim/Citizen" to "பாதிக்கப்பட்டவர்/குடிமகன்",
            "Access your journey & support" to "உங்கள் பயணம் மற்றும் ஆதரவை அணுகவும்",
            "Official Portal" to "அதிகாரப்பூர்வ போர்டல்",
            "Manage active case queues" to "செயலில் உள்ள வழக்கு வரிசைகளை நிர்வகிக்கவும்",
            "Preferred Language" to "விருப்பமான மொழி",
            "Select your communication language" to "உங்கள் தகவல் தொடர்பு மொழியைத் தேர்ந்தெடுக்கவும்",
            "Continue" to "தொடரவும்",
            "Your choice. Your control." to "உங்கள் தேர்வு. உங்கள் கட்டுப்பாடு.",
            "SAHAY-AI uses your check-ins to understand changes in your wellbeing. Your information is protected and accessed only by authorized personnel." to "உங்கள் நல்வாழ்வைப் புரிந்துகொள்ள சஹாய்-AI செக்-இன்களைப் பயன்படுத்துகிறது. தகவல் பாதுகாக்கப்படுகிறது.",
            "CONSENT-BASED — You choose whether to participate." to "சம்மதம் சார்ந்தது — நீங்கள் பங்கேற்பதா என்பதைத் தேர்ந்தெடுக்கிறீர்கள்.",
            "PRIVATE — Your information is protected." to "தனியுரிமை — உங்கள் தகவல் பாதுகாக்கப்படுகிறது.",
            "HUMAN SUPPORT — AI signals are reviewed by authorized people." to "மனித ஆதரவு — AI சிக்னல்கள் அதிகாரிகளால் மதிப்பாய்வு செய்யப்படுகின்றன.",
            "I understand and consent to wellbeing monitoring." to "நல்வாழ்வு கண்காணிப்பை நான் புரிந்துகொண்டு சம்மதிக்கிறேன்.",
            "Wellbeing monitoring requires your consent to continue." to "தொடர உங்கள் சம்மதம் தேவை.",
            "Give Consent" to "சம்மதம் கொடுங்கள்",
            "Not Now" to "இப்போது இல்லை",
            "Registration & Linkage" to "பதிவு மற்றும் இணைப்பு",
            "Link your secure case record" to "உங்கள் பாதுகாப்பான வழக்கு பதிவை இணைக்கவும்",
            "Full Name" to "முழு பெயர்",
            "Enter your full name" to "உங்கள் முழு பெயரை உள்ளிடவும்",
            "Mobile Number" to "கைபேசி எண்",
            "Enter your mobile number" to "உங்கள் மொபைல் எண்ணை உள்ளிடவும்",
            "Case ID" to "வழக்கு ஐடி",
            "Enter your case ID" to "உங்கள் வழக்கு ஐடியை உள்ளிடவும்",
            "Trusted Person’s Mobile Number" to "நம்பகமான நபரின் மொபைல் எண்",
            "Enter trusted person’s number" to "நம்பகமான நபரின் எண்ணை உள்ளிடவும்",
            "You may provide a trusted person’s number for urgent support. This is optional." to "அவசர ஆதரவுக்காக நம்பகமான நபரின் எண்ணை நீங்கள் வழங்கலாம். இது விருப்பமானது.",
            "Is this you? Log in securely" to "இது நீங்களா? பாதுகாப்பாக உள்நுழையவும்",
            "Link Profile" to "சுயவிவரத்தை இணை",
            "You’re all set" to "எல்லாம் தயார்",
            "Your details have been securely saved. You can now begin your wellbeing check-ins and access support." to "உங்கள் விவரங்கள் பாதுகாப்பாக சேமிக்கப்பட்டுள்ளன.",
            "Go to My Dashboard" to "என் டாஷ்போர்டுக்குச் செல்",
            "HOME" to "முகப்பு",
            "CHAT" to "அரட்டை",
            "JOURNEY" to "பயணம்",
            "SUPPORT" to "ஆதரவு",
            "PROFILE" to "சுயவிவரம்",
            "Good evening." to "மாலை வணக்கம்.",
            "How are you doing today?" to "இன்று நீங்கள் எப்படி இருக்கிறீர்கள்?",
            "TODAY'S CHECK-IN" to "இன்றைய செக்-இன்",
            "Take a moment to tell us how you are feeling." to "நீங்கள் எப்படி உணர்கிறீர்கள் என்பதை எங்களிடம் கூறவும்.",
            "Start Check-in" to "செக்-இன் தொடங்கவும்",
            "OTHER WAYS TO CONNECT" to "இணைவதற்கான பிற வழிகள்",
            "Talk to SAHAY" to "சஹாய் உடன் பேசுங்கள்",
            "VOICE" to "குரல்",
            "Speak instead" to "பதிலாக பேசுங்கள்",
            "CALL" to "அழைப்பு",
            "Scheduled Call" to "திட்டமிடப்பட்ட அழைப்பு",
            "Last Check-in" to "கடைசி செக்-இன்",
            "Distress Score" to "மனஅழுத்த மதிப்பெண்",
            "Distress Trend" to "மனஅழுத்தப் போக்கு",
            "Message SAHAY-AI..." to "சஹாய்-AI செய்தி அனுப்பு...",
            "Your Legal Journey" to "உங்கள் சட்ட பயணம்",
            "Case Status" to "வழக்கு நிலை",
            "Case Created" to "வழக்கு உருவாக்கப்பட்டது",
            "Timeline" to "காலக்கெடு",
            "Support Services" to "ஆதரவு சேவைகள்",
            "Emergency SOS" to "அவசரகால SOS",
            "Trigger immediate official response" to "உடனடி அதிகாரப்பூர்வ பதிலை தூண்டு",
            "Trusted Contacts" to "நம்பகமான தொடர்புகள்",
            "Profile & Settings" to "சுயவிவரம் மற்றும் அமைப்புகள்",
            "Secure Sign Out" to "பாதுகாப்பான வெளியேற்றம்",
            "Wellbeing Check-in" to "நல்வாழ்வு செக்-இன்",
            "Trend" to "போக்கு",
            "On a scale from 0 to 100, where 100 corresponds to extreme distress, how do you feel today?" to "0 முதல் 100 வரையிலான அளவுகோலில், இன்று எப்படி உணர்கிறீர்கள்?",
            "Score (0-100)" to "மதிப்பெண் (0-100)",
            "Submit Securely" to "பாதுகாப்பாக சமர்ப்பிக்கவும்",
            "Cancel" to "ரத்து செய்",
            "Stable" to "நிலையானது",
            "Supported" to "ஆதரவளிக்கப்பட்டது",
            "3 days ago" to "3 நாட்களுக்கு முன்பு",
            "Increasing" to "அதிகரித்து வருகிறது",
            "Improving" to "மேம்படுகிறது",
            "No distress data available yet." to "மனஅழுத்த தரவு இன்னும் கிடைக்கவில்லை.",
            "Complete more check-ins to see your distress trend." to "உங்கள் மனஅழுத்தப் போக்கைக் காண மேலும் செக்-இன்களை முடிக்கவும்.",
            "Your distress level across recent check-ins" to "சமீபத்திய செக்-இன்களில் உங்கள் மனஅழுத்த நிலை",
            "High" to "உயர்",
            "Low" to "குறைந்த",
            "Moderate" to "மிதமான",
            "Critical" to "மிகவும் ஆபத்தான",
            "How your score was calculated" to "உங்கள் மதிப்பெண் எவ்வாறு கணக்கிடப்பட்டது",
            "Risk Level" to "அபாய நிலை",
            "Contributing indicators:" to "பங்களிக்கும் குறிகாட்டிகள்:",
            "Potential concerns:" to "சாத்தியமான கவலைகள்:",
            "Emotional distress" to "உணர்ச்சி மன அழுத்தம்",
            "Fear/anxiety" to "பயம்/பதட்டம்",
            "Safety indicators" to "பாதுகாப்பு குறிகாட்டிகள்",
            "Engagement" to "ஈடுபாடு",
            "Change over time" to "காலப்போக்கில் மாற்றம்",
            "Total" to "மொத்தம்",
            "This is an AI-generated wellbeing indicator and NOT a medical diagnosis." to "இது AI ஆல் உருவாக்கப்பட்ட நல்வாழ்வு குறிகாட்டியாகும், இது மருத்துவ நோயறிதல் அல்ல.",
            "Insufficient data" to "போதிய தரவுகள் இல்லை",
            "Today" to "இன்று",
            "No Data" to "தரவு இல்லை",
            "Created" to "உருவாக்கப்பட்டது",
            "Case Created" to "வழக்கு உருவாக்கப்பட்டது",
            "Reviewed" to "மதிப்பாய்வு செய்யப்பட்டது",
            "Triaged" to "வகைப்படுத்தப்பட்டது",
            "Assigned" to "ஒதுக்கப்பட்டது",
            "Support Initiated" to "ஆதரவு தொடங்கப்பட்டது",
            "Follow-up" to "தொடர் நடவடிக்கை",
            "Resolved" to "தீர்க்கப்பட்டது",
            "Closed" to "மூடப்பட்டது",
            "Unknown" to "தெரியவில்லை"
        ),
        "தெలుగు" to mapOf(
            "SAHAY-AI" to "సహాయ్-AI",
            "Public Trust Infrastructure" to "పబ్లిక్ ట్రస్ట్ ఇన్ఫ్రాస్ట్రక్చర్",
            "Select Portal Access" to "పోర్టల్ యాక్సెస్ ఎంచుకోండి",
            "Victim/Citizen" to "బాధితుడు/పౌరుడు",
            "Access your journey & support" to "మీ ప్రయాణం మరియు మద్దతును యాక్సెస్ చేయండి",
            "Official Portal" to "అధికారిక పోర్టల్",
            "Manage active case queues" to "క్రియాశీల కేసు క్యూలను నిర్వహించండి",
            "Preferred Language" to "ప్రాధాన్య భాష",
            "Select your communication language" to "మీ కమ్యూనికేషన్ భాషను ఎంచుకోండి",
            "Continue" to "కొనసాగించండి",
            "Your choice. Your control." to "మీ ఇష్టం. మీ నియంత్రణ.",
            "SAHAY-AI uses your check-ins to understand changes in your wellbeing. Your information is protected and accessed only by authorized personnel." to "మీ క్షేమాన్ని అర్థం చేసుకోవడానికి SAHAY-AI మీ చెక్-ఇన్‌లను ఉపయోగిస్తుంది. మీ సమాచారం సురక్షితం.",
            "CONSENT-BASED — You choose whether to participate." to "సమ్మతి ఆధారిత - పాల్గొనాలా వద్దా మీ ఇష్టం.",
            "PRIVATE — Your information is protected." to "ప్రైవేట్ - మీ సమాచారం సురక్షితం.",
            "HUMAN SUPPORT — AI signals are reviewed by authorized people." to "మానవ మద్దతు - AI సంకేతాలను అధికారులు సమీక్షిస్తారు.",
            "I understand and consent to wellbeing monitoring." to "శ్రేయస్సు పర్యవేక్షణకు నేను అంగీకరిస్తున్నాను.",
            "Wellbeing monitoring requires your consent to continue." to "కొనసాగడానికి మీ సమ్మతి అవసరం.",
            "Give Consent" to "సమ్మతి ఇవ్వండి",
            "Not Now" to "ఇప్పుడు కాదు",
            "Registration & Linkage" to "నమోదు మరియు అనుసంధానం",
            "Link your secure case record" to "మీ సురక్షిత కేసు రికార్డును లింక్ చేయండి",
            "Full Name" to "పూర్తి పేరు",
            "Enter your full name" to "మీ పూర్తి పేరును నమోదు చేయండి",
            "Mobile Number" to "మొబైల్ సంఖ్య",
            "Enter your mobile number" to "మీ మొబైల్ నంబర్‌ను నమోదు చేయండి",
            "Case ID" to "కేసు ఐడి",
            "Enter your case ID" to "మీ కేసు ఐడిని నమోదు చేయండి",
            "Trusted Person’s Mobile Number" to "విశ్వసనీయ వ్యక్తి మొబైల్ నంబర్",
            "Enter trusted person’s number" to "విశ్వసనీయ వ్యక్తి నంబర్‌ను నమోదు చేయండి",
            "You may provide a trusted person’s number for urgent support. This is optional." to "మీరు అత్యవసర మద్దతు కోసం ఏ వ్యక్తి నంబర్‌నైనా అందించవచ్చు. ఇది ఐచ్ఛికం.",
            "Is this you? Log in securely" to "ఇది మీరేనా? సురక్షితంగా లాగిన్ అవ్వండి",
            "Link Profile" to "ప్రొఫైల్ లింక్ చేయండి",
            "You’re all set" to "అంతా సిద్ధంగా ఉంది",
            "Your details have been securely saved. You can now begin your wellbeing check-ins and access support." to "మీ వివరాలు సురక్షితంగా సేవ్ చేయబడ్డాయి. మీరు ఇప్పుడు ప్రారంభించవచ్చు.",
            "Go to My Dashboard" to "నా డాష్‌బోర్డ్‌కి వెళ్లండి",
            "HOME" to "హోమ్",
            "CHAT" to "చాట్",
            "JOURNEY" to "ప్రయాణం",
            "SUPPORT" to "మద్దతు",
            "PROFILE" to "ప్రొఫైల్",
            "Good evening." to "శుభ సాయంత్రం.",
            "How are you doing today?" to "ఈ రోజు మీరు ఎలా ఉన్నారు?",
            "TODAY'S CHECK-IN" to "ఈరోజు చెక్-ఇన్",
            "Take a moment to tell us how you are feeling." to "మీరు ఎలా భావిస్తున్నారో దయచేసి మాకు చెప్పండి.",
            "Start Check-in" to "చెక్-ఇన్ ప్రారంభించండి",
            "OTHER WAYS TO CONNECT" to "కనెక్ట్ చేయడానికి ఇతర మార్గాలు",
            "Talk to SAHAY" to "సహాయ్‌తో మాట్లాడండి",
            "VOICE" to "వాయిస్",
            "Speak instead" to "బదులుగా మాట్లాడండి",
            "CALL" to "కాల్",
            "Scheduled Call" to "షెడ్యూల్ చేసిన కాల్",
            "Last Check-in" to "చివరి చెక్-ఇన్",
            "Distress Score" to "డిస్ట్రెస్ స్కోరు",
            "Message SAHAY-AI..." to "సహాయ్-AIకి సందేశం ఇవ్వండి...",
            "Your Legal Journey" to "మీ చట్టపరమైన ప్రయాణం",
            "Case Status" to "కేసు స్థితి",
            "Timeline" to "కాలక్రమం",
            "Support Services" to "మద్దతు సేవలు",
            "Emergency SOS" to "అత్యవసర SOS",
            "Trigger immediate official response" to "తక్షణ అధికారిక ప్రతిస్పందనను ట్రిగ్గర్ చేయండి",
            "Trusted Contacts" to "విశ్వసనీయ పరిచయాలు",
            "Profile & Settings" to "ప్రొఫైల్ & సెట్టింగ్‌లు",
            "Secure Sign Out" to "సురక్షిత సైన్ అవుట్",
            "Wellbeing Check-in" to "శ్రేయస్సు చెక్-ఇన్",
            "On a scale from 0 to 100, where 100 corresponds to extreme distress, how do you feel today?" to "0 నుండి 100 స్కేల్‌పై, మీరు ఈ రోజు ఎలా భావిస్తున్నారు?",
            "Score (0-100)" to "స్కోరు (0-100)",
            "Submit Securely" to "సురక్షితంగా సమర్పించండి",
            "Cancel" to "రద్దు చేయండి",
            "Stable" to "స్థిరమైన",
            "Supported" to "మద్దతు"
        ),
        "മലയാളം" to mapOf(
            "SAHAY-AI" to "സഹായ്-AI",
            "Public Trust Infrastructure" to "പൊതു വിശ്വാസ അടിസ്ഥാന സൗകര്യം",
            // just English fallback for what isn't strictly requested (only Hindi, Tamil, Telugu requested, but Malayalam is in the list)
            "Select Portal Access" to "Select Portal Access"
        )
    )

    fun getString(key: String, language: String): String {
        return dict[language]?.get(key) ?: key
    }
}
